### PR TITLE
Fixes #60 adding RPI5 support

### LINKED ISSUE #60: Raspberry Pi 5
I've just installed my official raspberry pi touchscreen onto my new raspberry pi 5.  I kept getting this error:

```
pi@rpi5:~ $ rpi-backlight -b 100
Traceback (most recent call last):
  File "/usr/local/bin/rpi-backlight", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rpi_backlight/cli.py", line 80, in main
    backlight = Backlight(
                ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rpi_backlight/__init__.py", line 82, in __init__
    self._max_brightness = self._get_value("max_brightness")  # 255
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/rpi_backlight/__init__.py", line 99, in _get_value
    raise e
  File "/usr/local/lib/python3.11/dist-packages/rpi_backlight/__init__.py", line 91, in _get_value
    return int((self._backlight_sysfs_path / name).read_text())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1059, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1045, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/sys/class/backlight/rpi_backlight/max_brightness'
```

After some digging around a bit it looks like neither of these two folders exist on my rpi5:

`/sys/class/backlight/rpi_backlight`
`/sys/class/backlight/10-0045`

Instead, there is a folder called

`/sys/class/backlight/4-0045`

I was able to get it working when I changed the \_\_init\_\_.py files as follows:
```
_BACKLIGHT_SYSFS_PATHS = {
    BoardType.RASPBERRY_PI: (
        "/sys/class/backlight/4-0045/"
        if Path("/sys/class/backlight/4-0045/").exists()
        else "/sys/class/backlight/rpi_backlight/"
    ),
```

Whilst this worked for me, I have no idea how to implement a general solution for all pi models.

### PR DESCRIPTION
**Pull request by jamesecc**
Added 4-0045, 6-0045 alongside 10-0045 as per suggestion from [c899173-1024](https://github.com/c899173-1024)

### CODE REVIEW

**Comment by jamesecc** [comment]
@linusg I'm a noob when it comes to pull requests.  Please let me know if I should do / add anything else to this PR.

**Comment by JohnStov** [comment]
@linusg I would really appreciate it if you could merge this PR soon. Pi 5 support is getting critical for me.

**Comment by linusg** [comment]
Thanks, will tag a new release later today :)

**Comment by JohnStov** [comment]
That was very prompt! Thank you so much!

**Comment by jwanga** [comment]
@linusg Looks like a new release hasn't been cut yet. PyPi still shows 2.6.0 from 2022

**Comment by linusg** [comment]
Tagged a release on GitHub, PyPI will follow once https://github.com/pypi/support/issues/5201 is processed.

**Comment by jwanga** [comment]
Hey @linusg. Checking in on The PyPi update. Looks like it's still reporting 2.6.0. Also, the 2.7.0 release tag doesn't seem to include [#67](https://github.com/linusg/rpi-backlight/pull/67). Much appreciated!

**Pull request merged**
